# Generated by Django 3.2.7 on 2021-09-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idLocation', models.IntegerField()),
                ('barcode', models.CharField(max_length=11)),
                ('sku', models.CharField(max_length=17)),
                ('urunAdi', models.CharField(max_length=40)),
                ('locationCode', models.CharField(max_length=5)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
